workflows:
  ios-build:
    name: iOS KMP Build
    max_build_duration: 60
    environment:
      xcode: latest
    scripts:
      - name: Установка зависимостей
        script: |
          cd iosApp
          pod install  # Это выполнится на macOS через Codemagic
      - name: Сборка архива для iOS
        script: |
          cd iosApp
          xcodebuild -workspace iosApp.xcworkspace \
          -scheme iosApp \
          -configuration Release \
          -archivePath ./build/iosApp.xcarchive \
          archive
      - name: Экспорт .ipa
        script: |
          xcodebuild -exportArchive \
          -archivePath ./build/iosApp.xcarchive \
          -exportPath ./build \
          -exportOptionsPlist ./ExportOptions.plist
    artifacts:
      - iosApp/build/*.ipa