workflows:
  ios:
    name: Build iOS app
    environment:
      xcode: latest
    scripts:
      - name: Install dependencies
        script: |
          curl -sS https://get.sdkman.io | bash
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          sdk install kotlin
      - name: Build iOS app
        script: ./gradlew :iosApp:build
      - name: Run iOS Tests
        script: ./gradlew :iosApp:test