workflows:
  ios-workflow-id:
    name: iOS Test Build
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Build .ipa
        script: |
          flutter build ipa --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa