workflows:
  ios-build:
    name: iOS KMP Build
    max_build_duration: 60
    environment:
      kotlin: 1.9.0
      xcode: latest
      cocoapods: default
    scripts:
      - name: Установка зависимостей CocoaPods
        script: |
          cd iosApp
          pod install
      - name: Сборка архива для iOS
        script: |
          cd iosApp
          xcodebuild -workspace iosApp.xcodeproj \
          -scheme iosApp \
          -configuration Release \
          -archivePath ./build/iosApp.xcodeproj \
          archive
      - name: Экспорт .ipa
        script: |
          xcodebuild -exportArchive \
          -archivePath ./build/iosApp.xcodeproj \
          -exportPath ./build \
          -exportOptionsPlist ./ExportOptions.plist
    artifacts:
      - iosApp/build/*.ipa