workflows:
  ios-workflow-id:
    name: iOS Sample
    environment:
      vars:
        XCODE_WORKSPACE: "iosApp.xcodeproj" # Используй .xcodeproj, если нет .xcworkspace
        XCODE_SCHEME: "iosApp" # Название схемы
    scripts:
      - name: Cocoapods installation
        script: |
          cd $CM_BUILD_DIR/iosApp
          pod install
          - name: Set up code signing settings on Xcode project
            script: |
              xcode-project use-profiles
          - name: Build ipa for distribution
            script: |
              cd $CM_BUILD_DIR/iosApp
              xcode-project build-ipa \
                --workspace "$XCODE_WORKSPACE" \
                --scheme "$XCODE_SCHEME"
    artifacts:
      - iosApp/build/ios/ipa/*.ipa