workflows:
  ios-workflow-id:
    name: iOS Sample
    environment:
      vars:
        XCODE_WORKSPACE: "iosApp.xcodeproj" # Используй .xcodeproj, если нет .xcworkspace
        XCODE_SCHEME: "iosApp" # Название схемы
      xcode: latest # Или укажи конкретную версию, если нужно
    artifacts:
        - build/ios/ipa/*.ipa