workflows:
  ios:
    name: Build iOS app
    environment:
      flutter: stable
    platforms:
      ios:
        # Используем последнюю доступную версию Xcode
        xcode: latest
    steps:
      - checkout

      - run:
          name: Install dependencies
          script: |
            # Установим необходимые зависимости, например, Kotlin SDK
            curl -sS https://get.sdkman.io | bash
            source "$HOME/.sdkman/bin/sdkman-init.sh"
            sdk install kotlin

      - run:
          name: Build iOS app
          script: |
            # Выполним сборку проекта
            ./gradlew :iosApp:build

      - run:
          name: Run iOS Tests
          script: |
            # Запустим тесты для iOS
            ./gradlew :iosApp:test