workflows:
  ios-workflow-id:
    name: iOS Sample
    environment:
      vars:
        XCODE_WORKSPACE: "iosApp.xcodeproj" # Убедись, что имя верное
        XCODE_SCHEME: "iosApp" # Название схемы
      xcode:
        version: latest # Или укажи конкретную версию, если нужно
    scripts:
      - name: Install dependencies
        script: |
          cd iosApp
          pod install
      - name: Build iOS app
        script: |
          xcodebuild -workspace $XCODE_WORKSPACE -scheme $XCODE_SCHEME -configuration Release -sdk iphoneos archive -archivePath build/ios/iosApp.xcarchive
          xcodebuild -exportArchive -archivePath build/ios/iosApp.xcarchive -exportOptionsPlist iosApp/ExportOptions.plist -exportPath build/ios/iphoneos
    artifacts:
      - build/ios/iphoneos/*.ipa
      - build/ios/iphoneos/*.app
